### ISSUE TITLE
[Questions]

### ISSUE THREAD

**Issue by redtachyons** [rahulk11501/Alexa-Tracker#1]
Hi Rahul,
I have some questions regarding your code

Any particular reason to make send `POST` request for `search_alexa` , it just for fetching the data, right?

It seems that your data from aAlexa directly instead of storing it in local databas. This will make system slower, right? Also how you gonna get previous date's data

Is there any specific reason to put logic into controllers instead of using model, lib or services?

It seems like your ```RankingJob``` using just dummy data, Is it working progress? Or you forgot to commit that file?

Can you make logic like ```Ranking.all.map { |rank| rank.global_ranking}  ``` outside view layer?
Can you stub response from alexa in test suit?. Also can you extract alexa logic out of controller test

Thanks

**Comment by nithinbekal** [comment]
@rahulk11501 Just wanted to add some remarks to what @redtachyons has already mentioned.

- Right now your tests are calling Alexa API every time they are run. You might run the risk of exceeding API limits if you do that in tests. Can you think of a way to ensure that you're not making requests to a 3rd party API in tests?
- `RankingJob` effectively has the same responsibility as the controller logic, right? So if you extracted that out to a class, would that make it easier to use in both places?

**Comment by rahulk11501** [comment]
@redtachyons .. Initially I was going to store the ranking in database. But in that case we would have very less data to show in graph so I used dummy data. I can do all the changes you want. I didn't have time to make all the changes at that time. I had made the project in hurry as I told Imran. Also I have written Rspec of controller testing, which stub response from alexa.
